#include "tvm/tir/transform.h"
#include <tvm/ir/expr.h>
#include <tvm/ir/module.h>
#include <tvm/ir/type.h>
#include <tvm/node/functor.h>
#include <tvm/node/reflection.h>
#include <tvm/runtime/container/base.h>
#include <tvm/runtime/container/string.h>
#include <tvm/tir/buffer.h>
#include <tvm/tir/expr.h>
#include <tvm/tir/op.h>
#include <tvm/tir/stmt.h>
#include <tvm/tir/var.h>

namespace transform_test {

using tvm::Bool;
using tvm::make_object;
using tvm::ObjectRef;
using tvm::With;
using tvm::runtime::String;
using tvm::transform::Pass;
using tvm::transform::PassContext;
using tvm::transform::PassContextNode;
using tvm::transform::PassInfo;
using tvm::transform::PassInfoNode;
using tvm::transform::PassNode;
using tvm::transform::Sequential;

using tvm::tir::transform::AnnotateDeviceRegions;
using tvm::tir::transform::AnnotateEntryFunc;
using tvm::tir::transform::BF16ComputeLegalize;
using tvm::tir::transform::BF16StorageLegalize;
using tvm::tir::transform::BindParams;
using tvm::tir::transform::BindTarget;
using tvm::tir::transform::CombineContextCall;
using tvm::tir::transform::CommonSubexprElimTIR;
using tvm::tir::transform::CompactBufferAllocation;
using tvm::tir::transform::ConvertBlocksToOpaque;
using tvm::tir::transform::ConvertForLoopsToSerial;
using tvm::tir::transform::ConvertSSA;
using tvm::tir::transform::CreatePrimFuncPass;
using tvm::tir::transform::DecorateDeviceScope;
using tvm::tir::transform::DefaultGPUSchedule;
using tvm::tir::transform::ExtractPrimFuncConstants;
using tvm::tir::transform::Filter;
using tvm::tir::transform::FlattenBuffer;
using tvm::tir::transform::ForceNarrowIndexToInt32;
using tvm::tir::transform::FP8ComputeLegalize;
using tvm::tir::transform::FP8StorageLegalize;
using tvm::tir::transform::HoistExpression;
using tvm::tir::transform::HoistIfThenElse;
using tvm::tir::transform::InferFragment;
using tvm::tir::transform::InjectDoubleBuffer;
using tvm::tir::transform::InjectPermutedLayout;
using tvm::tir::transform::InjectPTXAsyncCopy;
using tvm::tir::transform::InjectPTXLDG32;
using tvm::tir::transform::InjectSoftwarePipeline;
using tvm::tir::transform::InjectVirtualThread;
using tvm::tir::transform::InlinePrivateFunctions;
using tvm::tir::transform::InstrumentBoundCheckers;
using tvm::tir::transform::InstrumentProfileIntrinsics;
using tvm::tir::transform::LegalizePackedCalls;
using tvm::tir::transform::LiftThreadBinding;
using tvm::tir::transform::LoopPartition;
using tvm::tir::transform::LowerAsyncDMA;
using tvm::tir::transform::LowerAutoCopy;
using tvm::tir::transform::LowerCrossThreadReduction;
using tvm::tir::transform::LowerCustomDatatypes;
using tvm::tir::transform::LowerDeviceKernelLaunch;
using tvm::tir::transform::LowerDeviceStorageAccessInfo;
using tvm::tir::transform::LowerInitBlock;
using tvm::tir::transform::LowerIntrin;
using tvm::tir::transform::LowerMatchBuffer;
using tvm::tir::transform::LowerOpaqueBlock;
using tvm::tir::transform::LowerThreadAllreduce;
using tvm::tir::transform::LowerTVMBuiltin;
using tvm::tir::transform::LowerVtcmAlloc;
using tvm::tir::transform::LowerWarpMemory;
using tvm::tir::transform::MakePackedAPI;
using tvm::tir::transform::MakeUnpackedAPI;
using tvm::tir::transform::ManifestSharedMemoryLocalStage;
using tvm::tir::transform::MergeSharedMemoryAllocations;
using tvm::tir::transform::NarrowDataType;
using tvm::tir::transform::PlanAndUpdateBufferAllocationLocation;
using tvm::tir::transform::PointerValueTypeRewrite;
using tvm::tir::transform::RemapThreadAxis;
using tvm::tir::transform::RemoveNoOp;
using tvm::tir::transform::RemoveWeightLayoutRewriteBlock;
using tvm::tir::transform::RenormalizeSplitPattern;
using tvm::tir::transform::RewriteUnsafeSelect;
using tvm::tir::transform::Simplify;
using tvm::tir::transform::SkipAssert;
using tvm::tir::transform::SplitHostDevice;
using tvm::tir::transform::StorageRewrite;
using tvm::tir::transform::ThreadSync;
using tvm::tir::transform::TransformMmaBufferLayout;
using tvm::tir::transform::UnifiedStaticMemoryPlanner;
using tvm::tir::transform::UnifyThreadBinding;
using tvm::tir::transform::UnrollLoop;
using tvm::tir::transform::UseAssumeToReduceBranches;
using tvm::tir::transform::VectorizeLoop;

using tvm::DataType;
using tvm::IntImm;
using tvm::IRModule;
using tvm::likely;
using tvm::PointerType;
using tvm::PrimExpr;
using tvm::PrimType;
using tvm::Range;
using tvm::ReflectionVTable;
using tvm::VoidType;
using tvm::runtime::Array;
using tvm::runtime::Downcast;
using tvm::runtime::Map;
using tvm::runtime::String;
using tvm::tir::Block;
using tvm::tir::Buffer;
using tvm::tir::BufferLoad;
using tvm::tir::BufferRegion;
using tvm::tir::BufferStore;
using tvm::tir::BufferType;
using tvm::tir::decl_buffer;
using tvm::tir::Evaluate;
using tvm::tir::For;
using tvm::tir::ForKind;
using tvm::tir::IfThenElse;
using tvm::tir::IterVar;
using tvm::tir::IterVarType;
using tvm::tir::PrimFunc;
using tvm::tir::Select;
using tvm::tir::SeqStmt;
using tvm::tir::SizeVar;
using tvm::tir::Stmt;
using tvm::tir::Var;

IRModule SimpleFor();
void TirVectorizeLoopTest();
void TirPartitionLoopTest();
void TirUnrollLoopTest();

}  // namespace transform_test
